### ISSUE TITLE
[FEATURE] Logo of SocialRepo

### ISSUE THREAD

**Issue by Param302** [Param302/SocialRepo#1]
## Description
I am thinking of a minimal logo, which should match the color scheme.
I don't have much knowledge about designs, so open to all suggestions. 😅

## Idea
I am having 2 ideas in my mind:
1. A simple neat logo just having the name Social Repo.
2. An inbox having stack of multiple social media icons in a translated manner.

If you have any other idea, you're welcome to share.

_Let's design the logo of SocialRepo_ 🙌

**Comment by porwalshreyaa** [comment]
I'll contribute in logo design.

**Comment by Param302** [comment]
Hey @porwalshreyaa let's move to [discussion](https://github.com/Param302/SocialRepo/discussions/4) tab, and discuss about the logo design there.

**Comment by Param302** [comment]
Hi @porwalshreyaa ,
I am assigning the logo work to you after the discussion.

Just to stay out of confusion, I am sharing the text and color palette.

## Color Palette
https://coolors.co/fefeff-9662ff-8c52ff-7029ff

### Color Palette for Logo
```
background: #7029FF
text:  #FFFFFF
```
## Logo Text
![Screenshot from 2024-05-06 19-46-51](https://github.com/Param302/SocialRepo/assets/76559816/d4676d63-b5b1-460b-aa8f-adb5c2209a1c)

The text should be in white color with purple background, rounded square works IMO. I am open to suggestions and ofcrse the final logo depends upon your creativity.

Take your time and make the logo, let me know if you need any help.

**Comment by porwalshreyaa** [comment]
![Uploading Copy of SocialRepo Logo.png…]()
