### ISSUE TITLE
[FEATURE] Create Social links container for Edit Panel of SocialRepo

### ISSUE THREAD

**Issue by Param302** [Param302/SocialRepo#10]
# Create links container using `HTML/CSS` for **Edit Panel**

## Description
Create the social links container as provided in the below image:
![Untitled - Design1 - Social Repo (another copy)](https://github.com/Param302/SocialRepo/assets/76559816/d302ed47-b7ac-4d25-a187-a1a253433e7a)

## Code
- Use `HTML/CSS` for creating and designing the container.
- Must follow the [**Code Guidelines**](https://github.com/Param302/SocialRepo/blob/main/.github/docs/README.md#code-guidelines) provided.
- Each container should be a list item (`li`) as a part of unordered list (`ul`) element.
- The unordered list (`ul`) element should be inside the **edit** section in `HTML`.
	```html
	<section id="edit">
	    <h2>Edit Panel</h2>
	</section>
	```
- To test the code, setup the extension by following [these](https://github.com/Param302/SocialRepo/blob/main/.github/docs/CONTRIBUTING.md#extension-setup) steps.
- Use the [**Color Palette**](https://github.com/Param302/SocialRepo/blob/main/.github/docs/README.md#color-theme) provided. You can add a light purple color as the background of container.
- Don't use favicons for arrow, rather download the relevant **png** arrow icon and store it in [`logos`](https://github.com/Param302/SocialRepo/tree/main/src/assets/logos) folder.
- The icon must not be more than `256x256` pixels.

### Additional
- Apply focus, hover effect.
- Replicate the containers to get visual appeal.
- Implement Scrollbar for Y-axis.

> **P.S**: This is just the designing part, no need to add any functionality as of now.

If you have any suggestion or idea, you're welcome to share.

_Let's design the SocialRepo social links container_ 🙌

**Comment by ThePlator** [comment]
I would like to work on this

**Comment by Param302** [comment]
> I would like to work on this 

Sure @ThePlator , Go ahead!

I am assigning you this issue, make sure that you've understood all the points listed in the issue and adhere to **CONTRIBUTING** guide.

**Comment by ronakptl996** [comment]
I completed it, please review, here is PR link : [https://github.com/Param302/SocialRepo/pull/12](LINK)

**Comment by Ayush031** [comment]
@Param302 is this issue solved?

**Comment by Param302** [comment]
> @Param302 is this issue solved?

Not yet!

@ThePlator if you are working on this, please share your progress.

**Comment by Param302** [comment]
> Good evening Param, i already have a solution ready for this issue, let me know if you would like me to send you the update by a pull request

Hey, please share your code or do the PR, as I can't see any fork of **SocialRepo** in your repositories.

**Comment by Abhinavpatra** [comment]
i just did if you find it suitable then assign it to me under gssoc'24

**Comment by ronakptl996** [comment]
Hey @Param302, I completed with drag and drop and copy the profile URL functionality. So, review it.

**Comment by Param302** [comment]
> i just did if you find it suitable then assign it to me under gssoc'24

Hey @Abhinavpatra ,
I guess there's some confusion, this repo is not under GSSOC'24 or any organization.
It's a normal community based project.
For the PR, I have commented the changes, please check

**Comment by Param302** [comment]
> @Param302 is this issue solved?

Hey @Ayush031 would you like to work on this issue?
