### ISSUE TITLE
[FEATURE] Implement Search Bar Design & Functionality for SocialRepo

### ISSUE THREAD

**Issue by Param302** [Param302/SocialRepo#28]
# Implement Search Bar Design & Functionality

## Overview
Implement the search bar design in `HTML/CSS` only as provided in the following image, with the **Add link button** functionality. Also, make it functional. Whenever a user types anything it should search the provided text in `li` list items i.e. link container, in both the link as well as in `alt` text of it's respective social media icon and show only those in the social media links container i.e. `ul`.

![image](https://github.com/Param302/SocialRepo/assets/76559816/8e9b618d-847f-4725-b7d6-75eebb1b98f8)

## Requirements
- Background color of parent container of search bar & add link button must be same as the background color of header. (Use declared CSS variables)
- The alignment of search bar and + (add link button) either be same as displayed in above image or you can be creative.
- Not the search bar should stays under the `edit` section only.
- Use Semantic `HTML`, avoid using `div` if possible.
- Remove `Edit Panel` text heading from `edit` section.
	```html
	<section id="edit">
		<!-- Search bar & add link button should be here -->
	</section>
	```
- Must follow the [**Code Guidelines**](https://github.com/Param302/SocialRepo/blob/main/.github/docs/README.md#code-guidelines) provided.
- Typing Anything in search bar must invoke a function in `JS` which searches the entered text in alt text of all social media icons as well as in the link of the user.
	- It should also display those `li` list items which has the entered text in `ul` container.
- If user cleared the search bar, then it should display all the social links `li` in `ul` container (which is default behaviour).
- To test the code, setup the extension by following [these](https://github.com/Param302/SocialRepo/blob/main/.github/docs/CONTRIBUTING.md#extension-setup) steps.
- Use the [**Color Palette**](https://github.com/Param302/SocialRepo/blob/main/.github/docs/README.md#color-theme) provided. You can add a light purple color as the background of container.
- Don't use favicons for add link button, rather download the relevant **png** add icon and store it in [`logos`](https://github.com/Param302/SocialRepo/tree/main/src/assets) folder.

### Additional
- Apply focus, hover and active effect on search bar & add link button
- Add padding for better visual of icons.

### 1
![image](https://github.com/Param302/SocialRepo/assets/76559816/7b958f46-93d5-4bff-80b0-9ac20b3bfa06)

### 2
![image](https://github.com/Param302/SocialRepo/assets/76559816/433a74df-e57d-4df4-b8e7-88cf42b5ed71)

If you have any suggestion or idea, you're welcome to share.

_Let's implement **SocialRepo**'s search functionality!_ 🙌

**Comment by HarshRaj2717** [comment]
Hey, I would like to work on this but am a bit busy rn, will come onto this by Tuesday evening and try to implement by end of the week.. you can assign this to me if it doesn't need to be implemented early.

**Comment by Jay-ARORA-5572** [comment]
I would like to contribute in this issue. Please assign to me #GSSoC2024



Add a comment

**Comment by Param302** [comment]
> I would like to contribute in this issue. Please assign to me #GSSoC2024
> 
> 
> 
> Add a comment

Hey @Jay-ARORA-5572 ,
Good to see that you want to contribute in this issue. But let me clarify you that this is not under GSSOC or any other program.

Let me know your confirmation and I will assign you this issue.

**Comment by Jay-ARORA-5572** [comment]
Ok if not from GSSoC, I still want to contribute.

**Comment by ghanashyam-r** [comment]
Hey @Param302 could you assign this issue to me

**Comment by Param302** [comment]
Sure @ghanashyam-r ,
I am assigning you this issue.

**Comment by ghanashyam-r** [comment]
Sorry i am a bit busy please assign this to someone else

**Comment by shubhusion** [comment]
Hi @Param302 , 
Assign this issue to me
