### ISSUE TITLE
[BUG] Fix social_apps.md File

### ISSUE THREAD

**Issue by Param302** [Param302/SocialRepo#39]
# Fix [`social_apps.md`](https://github.com/Param302/SocialRepo/blob/main/.github/docs/social-apps.md) File

## Description
Fix and update [`social_apps.md`](https://github.com/Param302/SocialRepo/blob/main/.github/docs/social-apps.md) file.

I have updated the format of [`social_apps.md`](https://github.com/Param302/SocialRepo/blob/main/.github/docs/social-apps.md) file with a new format.
Task is to fix it based upon the requirement.

### How to Fix?
Update the social media names rows 2nd and 3rd column based upon following requirement: 
1. If the social media profile URL is present in [`social_links.json`](https://github.com/Param302/SocialRepo/blob/main/src/social-links.json), update the 2nd column of that social media from ❌ to ✅
2. If the social media logo is present in [`assets/logos`](https://github.com/Param302/SocialRepo/tree/main/src/assets/logos) folder, update the 3rd column of that social media from ❌ to ✅

This fix is to make the things clear what details of each social media has been added.

**Comment by kirpaan** [comment]
Hi param assign me this task.
