### ISSUE TITLE
[FEATURE] Create a Link Validator

### ISSUE THREAD

**Issue by Param302** [Param302/SocialRepo#41]
# Create a Link Validator

## Overview
Create a link validator function in `JavaScript` for edit panel to validate the entered text, whether it's a valid link or not.
![image](https://github.com/Param302/SocialRepo/assets/76559816/efa2c609-cab9-4a1b-bc9a-810e1b7f44c7)

### What is the definition of a **Valid Link** :question: 
A link is valid if:
- The protocol should be `http` or `https` or `mailto`, i.e. the link the link should starts with.
- Protocol should be followed by `:` for `mailto` and `://` for `http` & `https`.

### Requirements:
- Create a function in JavaScript which calls whenever a user changes/types something in input box of the `link` container in `Edit` panel.
- The function must calls everytime on change of input, or whenever a user types something and shows the relevant output.
- Normally, the color of input's bottom border stays purple (`#7029ff`), it:
	- Changes to *red*, if the input text is not a valid link.
	- Changes to *green*, if the input text is a valid link.
- If the entered input is not a valid link, a text should be displayed under `input` tag, showing `Entered link is not valid`. It should not change the alignment, rather use `position: absolute` property.
- If the link is valid, the followed `preview` button should be enabled.
- Write the functionality in [`index.js`](https://github.com/Param302/SocialRepo/blob/main/src/code/index.js), style in [`style.css`](https://github.com/Param302/SocialRepo/blob/main/src/code/style.css).
- Must follow the [**Code Guidelines**](https://github.com/Param302/SocialRepo/blob/main/.github/docs/README.md#code-guidelines) provided.

### Resources
You can take help of [this](https://www.freecodecamp.org/news/how-to-validate-urls-in-javascript/) article.

## Important:
Do NOT change the existing layout/design or functionality.

If you have any suggestion or idea, you're welcome to share.

_Let's implement **SocialRepo**'s link validator!_ 🙌

**Comment by Subhoshri** [comment]
I want to work on this issue. Please assign it to me as I don't have any other ongoing issues.

**Comment by Param302** [comment]
> I want to work on this issue. Please assign it to me as I don't have any other ongoing issues.

Hey @Subhoshri sure!
I am assigning you this issue, you can work on it.

**Comment by Param302** [comment]
As @Thejas775 has contributed to this issue in #47 , I am closing this issue.
