### ISSUE TITLE
[FEATURE] Random Text Generator

### ISSUE THREAD

**Issue by Param302** [Param302/SocialRepo#43]
# Random Text Generator

## Overview
Create a random text generator which generates text for input's placeholder in edit panel.

![image](https://github.com/Param302/SocialRepo/assets/76559816/ad153507-d7e3-4f19-8a21-f0b5da04c98b)

```js
placeholderTexts = [
	"Paste your Social Handle here",
	"https://social.media/your_username",
	"Ctrl + V your social media profile",
	...
];
```

### Requirement
- Create a JavaScript function `randomTextGenerator()`, which uses `placeholderTexts` array and randomly returns any of the array item for place holder text.
- Add the `placeholderTexts` in [`index.js`](https://github.com/Param302/SocialRepo/blob/main/src/code/index.js) file.
- Add some more attractive placeholder texts in `placeHolderTexts` array to make it more random.
- Write the functionality in [`index.js`](https://github.com/Param302/SocialRepo/blob/main/src/code/index.js).
- Must follow the [**Code Guidelines**](https://github.com/Param302/SocialRepo/blob/main/.github/docs/README.md#code-guidelines) provided.

### Additional
Be creative! Add more placeholder texts to display on input element of `edit` panel.
You are free to use chatgpt or any other AI tools for texts, but make sure it should be in simple english, no complex words.

If you have any suggestion or idea, you're welcome to share.

_Let's implement **SocialRepo**'s placeholder random yet creative text generator!_ 🙌

**Comment by akashghadge** [comment]
I will work on this issue.
