### ISSUE TITLE
[FEATURE] Implement Add Link Box in Edit Panel

### ISSUE THREAD

**Issue by Param302** [Param302/SocialRepo#51]
# Implement Add Link Box in Edit Panel

## Description
Implement the add `link-box` feature for Edit Panel. Whenever user clicks on :heavy_plus_sign: button in edit panel, a new `link-box` will be created and added in `#links-container` ul (unordered list) at the top.

![image](https://github.com/Param302/SocialRepo/assets/76559816/e436a845-e43f-47f7-acf6-f7a8b8fd35fb)

![image](https://github.com/Param302/SocialRepo/assets/76559816/3802589e-1fb1-44c1-8555-5879bf7b591f)

### Requirements
- Whenever user clicks on `add-link-btn` button (:heavy_plus_sign:), a new `link-box` should be created via JS.
- The new `link-box` should be added to the top of `#links-container` ul (unordered list).
- The new `link-box` should be highlighted as shown in the 2nd image.
- The placeholder of `input` element should contain the random placeholder text which can be obtained via calling `getRandomPlaceholderText()`.
- By default, the image of `icon` class should be a `default.png` which should be 🌐 icon.
	- You can download this icon from the internet.
	- Icon should be maximum of `256x256` pixels.
	- Icon should be of `png` type.
	- Icon should be stored in [`assets/logos`](https://github.com/Param302/SocialRepo/tree/main/src/assets/logos) folder.
- All the JavaScript code should be written in [`index.js`](https://github.com/Param302/SocialRepo/blob/main/src/code/index.js)
- Do NOT modify any code `HTML/CSS` files.
- Must follow the [**Code Guidelines**](https://github.com/Param302/SocialRepo/blob/main/.github/docs/README.md#code-guidelines) provided.

### Structure
Structure of a `link-box` container is defined as follows:
```html
<li class="link-box">
    <img src="../assets/logos/drag.png" alt="dragger" class="dragger">
    <div class="link">
        <img src="../assets/logos/default.png" alt="default icon" class="icon">
        <input type="text" placeholder="<placeholder text>" />
        <button class="preview" disabled>
            <img src="../assets/logos/share.png" alt="preview link">
        </button>
    </div>
</li>
```

If you have any suggestion or idea, you're welcome to share.

_Let's implement **SocialRepo**'s add link box feature!_ 🙌

**Comment by shubhusion** [comment]
Hi @Param302 , 
assign this issue to me

**Comment by Param302** [comment]
> Hi @Param302 , 
> assign this issue to me 

Sure @shubhusion !

**Comment by DevvMaurya** [comment]
hi @Param302 
assign this to me.!
i can do it quickly.

**Comment by Param302** [comment]
> hi @Param302 
> assign this to me.!
> i can do it quickly.

Hey @DevvMaurya ,
I appreciate your enthusiasm but this issue is already assigned, you can work on other issues, there are various issues to contribute.

https://github.com/Param302/SocialRepo/issues

**Comment by shubhusion** [comment]
Hi @Param302,

Due to other work commitments, I will be unable to complete it within the next 2-3 days. If you need it done urgently, please ask @DevvMaurya to handle it. If he is unable to do so, I will take care of it once I am available.

**Comment by Param302** [comment]
> Hi @Param302,
> 
> Due to other work commitments, I will be unable to complete it within the next 2-3 days. If you need it urgently, please ask @DevvMaurya to handle it. If he is unable to do so, I will take care of it once I am available.

Oh oky no worries!

@DevvMaurya are you still up for this?
Let me know I will assign you the issue.

**Comment by DevvMaurya** [comment]
Okay.! I'm ready..!

**Comment by Param302** [comment]
> @Param302 
> Okay.! I'm ready..!

Oky, super fast 😅
Appreciated!

I will check the PR soon

**Comment by DevvMaurya** [comment]
@Param302 
Actually I already fixed this issue in my free hour😅.
take a look.

![image](https://github.com/Param302/SocialRepo/assets/105772302/eb437a3e-8bdf-4824-8e5d-06d7fa544aac)

**Comment by Param302** [comment]
> @Param302 
> Actually I already fixed this issue in my free hour😅.
> take a look.
> 
> ![image](https://github.com/Param302/SocialRepo/assets/105772302/eb437a3e-8bdf-4824-8e5d-06d7fa544aac)
> 

Great, just do the Pull Request, I will merge it.
