### ISSUE TITLE
[FEATURE] SocialRepo Logo Variants for different sizes

### ISSUE THREAD

**Issue by Param302** [Param302/SocialRepo#7]
## Description
As part of improving the visual consistency and scalability of the SocialRepo extension, we need to create logo variants in various sizes to ensure optimal display across different contexts and screen resolutions.

You only need to create different size logos for [`logo.png`](https://github.com/Param302/SocialRepo/blob/main/src/assets/logos/logo.png)

### Tasks
Create logo variants in the following sizes:
- [ ] 16x16 pixels
- [ ] 32x32 pixels
- [ ] 48x48 pixels
- [ ] 128x128 pixels

After creating the logos, add them in [`assets/logos`](https://github.com/Param302/SocialRepo/tree/main/src/assets/logos) folder.

### Resources
You can resize logo from this website.
https://imresizer.com/download

**P.S**: Make sure the logo should be transparent.

**Comment by fabiomughilan** [comment]
Hi @Param302 
I can do this. Can you assign me this issue

**Comment by nancyvaryani** [comment]
Hey @Param302  , I can do this! If the issue is not resolved, can you assign me this issue?

**Comment by Param302** [comment]
> Hi @Param302 I can do this. Can you assign me this issue

Hey @fabiomughilan ,
I saw you've already contributed and completed this issue, I am merging your PR to main branch.

Thanks for contributing!

Although from next time, please wait for the maintainers to assign you the issue before doing the PR, as it will help us (the maintainers) keep the track.

**Comment by Param302** [comment]
> Hey @Param302 , I can do this! If the issue is not resolved, can you assign me this issue?

Hey this issue is completed, you can work on other issues listed [here](https://github.com/Param302/SocialRepo/issues/).
